---
title: "Kelp stressors paper life-cycle figure"
author: "Kelly Andrews"
date: "4/12/2021"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Life cycle figure for kelp stressors paper

This creates pie charts showing literature review results by life cycle stage and direct stressors (Pressures) on kelp habitats.

Packages needed:
```{r packages}
library(tidyverse)
library(ggforce)
library(ggpubr)
library(patchwork)
library(png)
library(tinytex)
```

Import data
```{r import and manipulate data}
dat <- read.csv("data/life cycle literature stats for figure 2.csv", header = TRUE)

#pivot data and change factor level order of lifestages to get in correct life-cycle order
dat <- dat %>%
  pivot_longer(cols = c("Adults","Zoospores","Gametophytes","Juveniles"),
               names_to = "lifestage",
               values_to = "papers") %>%
  mutate(lifestage = factor(lifestage, levels = c("Adults", "Zoospores", "Gametophytes", "Juveniles")))
```

Calculate angle position for each pie
```{r calculate angles}
dat_pies <- left_join(dat,
                      dat %>% 
                        group_by(Stressor) %>%
                        summarize(Cnt_total = sum(papers))) %>%
  group_by(Stressor) %>%
  mutate(end_angle = 2*pi*cumsum(papers)/Cnt_total,      # ending angle for each pie slice
         start_angle = lag(end_angle, default = 0),   # starting angle for each pie slice
         mid_angle = 0.5*(start_angle + end_angle))   # middle of each pie slice, for the text label
```

Label locations and rotation parameters
```{r labels and rotation parameters}
rpie = 1 # pie radius
rlabel = c(rep(0.7 * rpie, 20), 1.1, rep(0.7 * rpie, 4)) # radius of the labels - 0.5 would place it exactly in the middle, but a number slightly larger than 0.5 seems to look better. This gives each label a value so that I could move numbers to the outside edge of the pie if its slice was too tiny to hold the value. 
rot = pi * 1.1  #in order to keep adults in the left/upper portion of all the pies; larger values for "rot" rotate Adult's lower starting point clockwise
```

```{r figure code, echo=FALSE, fig.width=13, fig.height=7}
# draw the pies
  p1 <- ggplot(dat_pies %>%
         filter(papers != 0)) +
                #Stressor %in% c("Algal competition", "Benthic sediment", "Contaminants", "Epiphytes", "Mechanical damage"))) + 
  geom_arc_bar(aes(x0 = 0, y0 = 0, r0 = 0, r = rpie,
                   start = start_angle + rot, end = end_angle + rot, fill = lifestage),
               color = "white") +
  geom_text(aes(x = rlabel*sin(mid_angle + rot), y = rlabel*cos(mid_angle + rot), 
                label = papers),
            hjust = 0.5, vjust = 0.5) +
  coord_fixed() +
  scale_fill_manual(values = c("#0072B2", "#009E73", "#E69F00", "#CC79A7")) +
  facet_wrap(. ~ Stressor, ncol = 3, 
             labeller = label_wrap_gen(width = 12), 
             dir = "h", 
             strip.position = "top") +
  theme_minimal() +
  theme(plot.margin=grid::unit(c(0,0,0,0), "in"),
        legend.position = "none",
        panel.background = element_blank(),
        panel.grid = element_blank(),
        strip.text = element_text(size = 12, face = "bold"),
        axis.title = element_blank(),
        axis.text = element_blank())
#p1  

#import life cycle image provided by Su Kim
lc <- readPNG("data/Bull kelp life cycle.png")

lc <- ggplot() +
  theme_void() +
  background_image(lc) +
  theme(plot.margin = unit(c(0,0,0,0), "lines")) +
  coord_fixed()

lc + p1 + plot_layout(widths = c(1,1)) + plot_annotation(tag_levels = 'A')
```
Save plot
```{r save image}
png("Figure 3. Life cycle literature stats.png", width = 13, height = 7, units = "in", res = 300)
lc + p1 + plot_layout(widths = c(1,1)) + plot_annotation(tag_levels = 'A')
dev.off()

```

